export interface AiTool {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'generate' | 'creative' | 'social' | 'business';
  type: 'text-to-image' | 'template-based';
  gradient: string;
  promptPrefix: string;
  promptSuffix: string;
  sizes: { label: string; w: number; h: number }[];
  defaultSize: string;
  styles: string[];
  suggestions: string[];
}

export const categoryLabels: Record<string, string> = {
  'generate': 'AI Generation',
  'creative': 'Creative Studio',
  'social': 'Social Media',
  'business': 'Business Tools',
};

export const tools: AiTool[] = [
  {
    id: 'text-to-image',
    name: 'Text to Image',
    description: 'Generate any image from a text description using AI.',
    icon: '🖼️',
    category: 'generate',
    type: 'text-to-image',
    gradient: 'bg-gradient-to-br from-purple-500/20 to-pink-500/20',
    promptPrefix: '',
    promptSuffix: ', high quality, detailed, 4k',
    sizes: [
      { label: '1:1', w: 1024, h: 1024 },
      { label: '16:9', w: 1344, h: 768 },
      { label: '9:16', w: 768, h: 1344 },
      { label: '4:3', w: 1152, h: 896 },
    ],
    defaultSize: '1:1',
    styles: ['Photorealistic', 'Digital Art', 'Anime', 'Oil Painting', 'Watercolor', '3D Render', 'Pixel Art', 'Sketch'],
    suggestions: [
      'A serene mountain lake at golden hour with reflections',
      'Futuristic cyberpunk cityscape with neon lights and flying cars',
      'A cozy coffee shop interior with rain on the windows',
      'Majestic dragon flying over a medieval castle at sunset',
      'Underwater coral reef with colorful tropical fish',
    ],
  },
  {
    id: 'ai-avatar',
    name: 'AI Avatar Maker',
    description: 'Create unique AI-generated avatars and profile pictures.',
    icon: '👤',
    category: 'creative',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-purple-500/20 to-fuchsia-500/20',
    promptPrefix: 'portrait of a person, ',
    promptSuffix: ', avatar, profile picture, clean background, high quality',
    sizes: [
      { label: '1:1', w: 1024, h: 1024 },
    ],
    defaultSize: '1:1',
    styles: ['Photorealistic', 'Anime', 'Cartoon', '3D Character', 'Watercolor Portrait', 'Cyberpunk', 'Fantasy', 'Minimalist'],
    suggestions: [
      'Young woman with colorful hair and glowing eyes',
      'Bearded man wearing a leather jacket, urban background',
      'Elderly man with kind eyes and a warm smile',
      'Futuristic android with metallic features and blue eyes',
      'Warrior princess with ornate armor and flowing hair',
    ],
  },
  {
    id: 'ai-logo',
    name: 'AI Logo Creator',
    description: 'Generate professional logos for brands and projects.',
    icon: '💎',
    category: 'business',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-amber-500/20 to-orange-500/20',
    promptPrefix: 'professional logo design for ',
    promptSuffix: ', minimalist, vector style, clean, white background, high quality logo',
    sizes: [
      { label: '1:1', w: 1024, h: 1024 },
      { label: '16:9', w: 1344, h: 768 },
    ],
    defaultSize: '1:1',
    styles: ['Minimalist', 'Modern', 'Retro', 'Luxury', 'Tech', 'Playful', 'Nature', 'Abstract'],
    suggestions: [
      'a coffee shop called Sunrise Brew',
      'a tech startup called CloudSync',
      'a fitness brand called IronPulse',
      'a photography studio called LensCraft',
      'a music app called BeatWave',
    ],
  },
  {
    id: 'ai-wallpaper',
    name: 'AI Wallpaper Generator',
    description: 'Create stunning wallpapers for desktop and mobile.',
    icon: '🖥️',
    category: 'creative',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-sky-500/20 to-purple-500/20',
    promptPrefix: 'wallpaper, ',
    promptSuffix: ', stunning, high resolution, wallpaper quality, 4k, no text',
    sizes: [
      { label: 'Desktop 16:9', w: 1920, h: 1080 },
      { label: 'Mobile 9:16', w: 1080, h: 1920 },
      { label: 'Square 1:1', w: 1024, h: 1024 },
    ],
    defaultSize: 'Desktop 16:9',
    styles: ['Nature', 'Abstract', 'Space', 'Dark & Moody', 'Vibrant', 'Minimalist', 'Gradient', 'Anime'],
    suggestions: [
      'Aurora borealis over a snow-covered mountain range',
      'Abstract geometric shapes with purple and teal gradients',
      'Deep space nebula with colorful cosmic clouds',
      'Cherry blossom petals floating over a calm river',
      'Dark minimalist landscape with a single glowing tree',
    ],
  },
  {
    id: 'ai-thumbnail',
    name: 'AI YouTube Thumbnail',
    description: 'Generate eye-catching thumbnails for YouTube videos.',
    icon: '🎬',
    category: 'social',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-red-500/20 to-orange-500/20',
    promptPrefix: 'YouTube thumbnail, ',
    promptSuffix: ', bold, eye-catching, vibrant colors, high contrast, clickbait style, high quality',
    sizes: [
      { label: '16:9', w: 1280, h: 720 },
    ],
    defaultSize: '16:9',
    styles: ['Bold & Bright', 'Dark & Dramatic', 'Clean & Professional', 'Gaming', 'Vlog Style', 'Tutorial', 'Reaction', 'Comparison'],
    suggestions: [
      'Shocked person looking at a huge pile of money',
      'Before and after fitness transformation split screen',
      'Unboxing a glowing mysterious tech gadget',
      'Person pointing at an explosion of colorful particles',
      'Dramatic comparison between two smartphones with arrows',
    ],
  },
  {
    id: 'ai-social',
    name: 'AI Social Media Post',
    description: 'Create Instagram, Twitter, and LinkedIn post images.',
    icon: '📱',
    category: 'social',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-pink-500/20 to-rose-500/20',
    promptPrefix: 'social media post image, ',
    promptSuffix: ', professional, modern, visually appealing, social media quality',
    sizes: [
      { label: 'Instagram Post 1:1', w: 1080, h: 1080 },
      { label: 'Instagram Story 9:16', w: 1080, h: 1920 },
      { label: 'Twitter/X 16:9', w: 1200, h: 675 },
      { label: 'LinkedIn 4:3', w: 1200, h: 900 },
    ],
    defaultSize: 'Instagram Post 1:1',
    styles: ['Lifestyle', 'Business', 'Motivational', 'Product', 'Event', 'Minimalist', 'Vibrant', 'Elegant'],
    suggestions: [
      'Motivational quote card with sunrise background',
      'New product launch announcement with sleek design',
      'Behind the scenes workspace setup photo',
      'Team celebration with confetti and bright colors',
      'Travel destination showcase with warm golden tones',
    ],
  },
  {
    id: 'ai-art',
    name: 'AI Art Studio',
    description: 'Create museum-quality digital art in any style.',
    icon: '🎨',
    category: 'creative',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-violet-500/20 to-purple-500/20',
    promptPrefix: 'fine art, ',
    promptSuffix: ', masterpiece, gallery quality, highly detailed, artistic',
    sizes: [
      { label: '1:1', w: 1024, h: 1024 },
      { label: '3:4', w: 896, h: 1152 },
      { label: '4:3', w: 1152, h: 896 },
    ],
    defaultSize: '1:1',
    styles: ['Impressionism', 'Surrealism', 'Renaissance', 'Baroque', 'Art Nouveau', 'Pop Art', 'Cubism', 'Japanese Ukiyo-e'],
    suggestions: [
      'Starry night over a floating island with waterfalls',
      'Surreal desert with melting clocks and giant flowers',
      'Renaissance-style portrait of a modern woman with tattoos',
      'Japanese wave painting with Mount Fuji and cherry blossoms',
      'Pop art collage of modern technology and nature merging',
    ],
  },
  {
    id: 'ai-icon',
    name: 'AI Icon Generator',
    description: 'Generate app icons, favicons, and UI icons with AI.',
    icon: '⚡',
    category: 'business',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-emerald-500/20 to-teal-500/20',
    promptPrefix: 'app icon design, ',
    promptSuffix: ', icon, rounded corners, clean, simple, bold, no text, single object, flat design',
    sizes: [
      { label: '1:1', w: 1024, h: 1024 },
    ],
    defaultSize: '1:1',
    styles: ['Flat Design', 'Gradient', 'Glassmorphism', 'Neumorphism', 'Retro', 'Minimalist', '3D', 'Line Art'],
    suggestions: [
      'A lightning bolt inside a circle for a fitness app',
      'A camera lens with a rainbow ring for a photo app',
      'A chat bubble with a heart for a messaging app',
      'A musical note with sound waves for a music app',
      'A shield with a checkmark for a security app',
    ],
  },
  {
    id: 'ai-meme',
    name: 'AI Meme Creator',
    description: 'Generate funny meme templates and meme-style images.',
    icon: '😂',
    category: 'social',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-yellow-500/20 to-amber-500/20',
    promptPrefix: 'meme template, funny, ',
    promptSuffix: ', meme style, humorous, reaction image, high quality, no text',
    sizes: [
      { label: '1:1', w: 1024, h: 1024 },
      { label: '16:9', w: 1280, h: 720 },
    ],
    defaultSize: '1:1',
    styles: ['Classic Meme', 'Reaction', 'Wholesome', 'Sarcastic', 'Relatable', 'Cringe', 'Wholesome', 'Dark Humor'],
    suggestions: [
      'Cat sitting at a desk looking very confused at a laptop',
      'Dog wearing sunglasses looking cool on the beach',
      'Person surrounded by 5 alarms going off in the morning',
      'Two people shaking hands while a third watches suspiciously',
      'Person trying to sleep while a notification keeps popping up',
    ],
  },
  {
    id: 'ai-product',
    name: 'AI Product Photo',
    description: 'Generate professional product photography with AI.',
    icon: '📦',
    category: 'business',
    type: 'template-based',
    gradient: 'bg-gradient-to-br from-cyan-500/20 to-blue-500/20',
    promptPrefix: 'professional product photography, ',
    promptSuffix: ', studio lighting, clean background, commercial quality, e-commerce photo',
    sizes: [
      { label: '1:1', w: 1024, h: 1024 },
      { label: '4:3', w: 1152, h: 896 },
      { label: '16:9', w: 1344, h: 768 },
    ],
    defaultSize: '1:1',
    styles: ['White Background', 'Lifestyle', 'Flat Lay', 'Minimalist', 'Luxury', 'Natural', 'Colorful', 'Dark & Moody'],
    suggestions: [
      'A sleek smartwatch on a marble surface with soft shadows',
      'Skincare products arranged on a wooden table with plants',
      'Running shoes on a gradient background with motion blur',
      'Perfume bottle with water droplets and golden light',
      'Wireless earbuds floating with a soft glow around them',
    ],
  },
];